name: Trigger Repo A on Push

on:
  push:
    branches:
      - main

jobs:
  trigger_repo_a:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event to docs repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_DOCS }}
          repository: salomob-dynasafe/mkdocs-githubpages # Replace with Repo A's owner/repo name
          event-type: docs-update # A custom event type to identify this trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
